In [10]:
import numpy as np
import pandas as pd
# import torch
# import torch.nn as nn
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report
# import transformers
# from transformers import AutoModel, BertTokenizerFast

# # specify GPU
# device = torch.device("cuda")

In [11]:
df = pd.read_csv("spam.csv")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [12]:
df = df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis = 1)

In [13]:
df.head(10)

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [5]:
df.groupby('v1').describe()

v2                                                               
     count unique                                                top freq
v1                                                                       
ham   4825   4516                             Sorry, I'll call later   30
spam   747    653  Please call our customer service representativ...    4

In [6]:
df.groupby('v2').describe()

v1                  
                                                   count unique   top freq
v2                                                                        
 &lt;#&gt;  in mca. But not conform.                   1      1   ham    1
 &lt;#&gt;  mins but i had to stop somewhere fi...     1      1   ham    1
 &lt;DECIMAL&gt; m but its not a common car her...     1      1   ham    1
 and  picking them up from various points              1      1   ham    1
 came to look at the flat, seems ok, in his 50s...     1      1   ham    1
 gonna let me know cos comes bak from holiday t...     1      1   ham    1
 said kiss, kiss, i can't do the sound effects!...     1      1   ham    1
 says that he's quitting at least5times a day s...     1      1   ham    1
 what number do u live at? Is it 11?                   1      1   ham    1
&lt;#&gt;  am I think? Should say on syllabus          1      1   ham    1
&lt;#&gt;  great loxahatchee xmas tree burning ...     1      1   ham    1
&lt;#&gt;  is fast approaching. So, Wish u a ve...     1      1   ham    1
&lt;#&gt;  w jetton ave if you forgot                  1      1   ham    1
&lt;#&gt; %of pple marry with their lovers... b...     1      1   ham    1
&lt;#&gt; , that's all? Guess that's easy enough       1      1   ham    1
&lt;#&gt; ISH MINUTES WAS 5 MINUTES AGO. WTF.          1      1   ham    1
'An Amazing Quote'' - \Sometimes in life its di...     1      1   ham    1
'Wnevr i wana fal in luv vth my books, My bed f...     1      1   ham    1
(And my man carlos is definitely coming by mu t...     1      1   ham    1
(Bank of Granite issues Strong-Buy) EXPLOSIVE P...     1      1  spam    1
(I should add that I don't really care and if y...     1      1   ham    1
(No promises on when though, haven't even gotte...     1      1   ham    1
(That said can you text him one more time?)            1      1   ham    1
(You didn't hear it from me)                           1      1   ham    1
* Am on a train back from northampton so i'm af...     1      1   ham    1
* Am on my way                                         1      1   ham    1
* FREE* POLYPHONIC RINGTONE Text SUPER to 87131...     1      1  spam    1
* Thought I didn't see you.                            1      1   ham    1
* Was a nice day and, impressively, i was sensi...     1      1   ham    1
* Was really good to see you the other day dude...     1      1   ham    1
...                                                  ...    ...   ...  ...
yes baby! I need to stretch open your pussy!           1      1   ham    1
you are sweet as well, princess. Please tell me...     1      1   ham    1
�� all write or wat..                                  1      1   ham    1
�� bot notes oredi... Cos i juz rem i got...           1      1   ham    1
�� called dad oredi...                                 1      1   ham    1
�� collecting ur laptop then going to configure...     1      1   ham    1
�� come lt 25 n pass to me lar                         1      1   ham    1
�� comin to fetch us oredi...                          1      1   ham    1
�� dun need to pick ur gf?                             1      1   ham    1
�� dun wan to watch infernal affair?                   1      1   ham    1
�� eatin later but i'm eatin wif my frens now l...     1      1   ham    1
�� give me some time to walk there.                    1      1   ham    1
�� go home liao? Ask dad to pick me up at 6...         1      1   ham    1
�� got wat to buy tell us then �_ no need to co...     1      1   ham    1
�� log off 4 wat. It's sdryb8i                         1      1   ham    1
�� mean it's confirmed... I tot they juz say on...     1      1   ham    1
�� neva tell me how i noe... I'm not at home in...     1      1   ham    1
�� no home work to do meh...                           1      1   ham    1
�� only send me the contents page...                   1      1   ham    1
�� predict wat time �_'ll finish buying?               1      1   ham    1
�� r

In [14]:
df['spam'] = df['v1'].apply(lambda x: 1 if x == 'spam' else 0)
df.head(15)

v1                                                 v2  spam
0    ham  Go until jurong point, crazy.. Available only ...     0
1    ham                      Ok lar... Joking wif u oni...     0
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3    ham  U dun say so early hor... U c already then say...     0
4    ham  Nah I don't think he goes to usf, he lives aro...     0
5   spam  FreeMsg Hey there darling it's been 3 week's n...     1
6    ham  Even my brother is not like to speak with me. ...     0
7    ham  As per your request 'Melle Melle (Oru Minnamin...     0
8   spam  WINNER!! As a valued network customer you have...     1
9   spam  Had your mobile 11 months or more? U R entitle...     1
10   ham  I'm gonna be home soon and i don't want to tal...     0
11  spam  SIX chances to win CASH! From 100 to 20,000 po...     1
12  spam  URGENT! You have won a 1 week FREE membership ...     1
13   ham  I've been searching for the right words to tha...     0
14   ham                I HAVE A DATE ON SUNDAY WITH WILL!!     0

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['v2'], df['spam'], test_size=0.25)

In [16]:
## Now proceeding to make use of COunt vectorizer (try to use word2vec, bert also)
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]




array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
emails = ["Hey Dhruv, it was great meeting you today. I hope we can discuss further and plan on what songs we woud like to perform for our College fest. Regards",
          "Free Parking at new mall!! Tap this link to avail full discount and get a chance to win a Dubai trip for 10 days.. absolutely 0 cost!!"
         ]


In [24]:
emails[1]

'Free Parking at new mall!! Tap this link to avail full discount and get a chance to win a Dubai trip for 10 days.. absolutely 0 cost!!'

In [25]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [26]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9834888729361091

In [27]:
from sklearn.pipeline import Pipeline

In [28]:
clf = Pipeline([('vectorizer', CountVectorizer()), 
               ('nb', MultinomialNB())
               ])

In [29]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9834888729361091

In [30]:
clf.predict(emails)

array([0, 1], dtype=int64)